### ISSUE TITLE
Editing broken file links doesn’t work

### ISSUE THREAD

**Issue by lozcalver** [kinglozzer/htmleditoruploadfield#2]
Can’t attach a file to the `UploadField` if the file doesn’t exist :(

![screen shot 2015-09-09 at 09 29 01](https://cloud.githubusercontent.com/assets/1655548/9756946/93acc33e-56d5-11e5-9f69-c247a0e928a9.png)

**Comment by lozcalver** [comment]
https://github.com/silverstripe/silverstripe-framework/pull/4594

**Comment by tractorcow** [comment]
Fixed with #4594

**Comment by lozcalver** [comment]
:+1:
